version: "3.8"

services:
  dnsmasq:
    image: alpine:3.18
    restart: unless-stopped
    network_mode: host # port: 5453
    volumes:
      - /tmp/dnsmasq:/tmp/dnsmasq:rw
    environment:
      - CFG_FILE=/etc/dnsmasq.d/dns.conf
      - DHCP_LEASES=/tmp/dnsmasq/dhcp.leases
      - DNS_LOGS=/tmp/dnsmasq/log.fifo
      - DNS_SERVERS=1.1.1.1 8.8.8.8
      - DNS_CACHE_SIZE=1000
      - DNS_CACHE_TTL=25
    entrypoint: ["/bin/ash", "-euxo", "pipefail", "-c"]
    command:
      - |
        apk add --update --no-cache dnsmasq bind-tools

        echo -e "listen-address=127.0.0.1\nport=5453\ncache-size=$${DNS_CACHE_SIZE}\nno-negcache\nmin-cache-ttl=$${DNS_CACHE_TTL}\nmax-cache-ttl=$${DNS_CACHE_TTL}\nno-hosts\nno-resolv\nstrict-order\nlog-queries=extra\nlog-async=100\nlog-facility=$${DNS_LOGS}" > "$${CFG_FILE}"
        for srv in $${DNS_SERVERS}; do echo "server=$${srv}" >> "$${CFG_FILE}"; done
        cat "$${CFG_FILE}"

        echo "1701658085 10:2b:41:04:88:95 192.168.1.3 some-host-name 01:10:2b:41:04:88:95" > "$${DHCP_LEASES}"

        if ! [ -p "$${DNS_LOGS}" ]; then mkfifo -m 644 "$${DNS_LOGS}"; fi
        dnsmasq --conf-file="$${CFG_FILE}"

        while sleep 10; do dig +short @127.0.0.1 -p 5453 onet.pl; done
